import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from 'next-themes'
import Header from '@/components/Header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Header />
              <main className='flex flex-col items-center'>
                <div className='w-full max-w-5xl'>
                  <div className='max-w-auto mx-auto'>{children}</div>
                </div>
              </main>
              <footer className="bg-gray-400 py-4 px-8 mt-20">
                <p className="text-center">
                  본 페이지는 상업적 목적이 아닌 개인 포트폴리오용으로 제작되었습니다. <br />
                  © 2025 Jo Eun-Su. All Rights Reserved.
                </p>
              </footer>
        </body>
      </html>
    </ClerkProvider>
  )
}